решил первые 4 задачи, последнюю пока не осилил
js-tasks-ru/jsbasic-20240808_sergey-b0 pull request #1
Opened 2024-08-11 21:11 UTC by sebotest3

2024-08-11 21:11 UTC, jsru-1 commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2024-08-12 11:40 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-08-12 13:01 UTC, SinimaWath requested changes

2024-08-12 13:01 UTC, SinimaWath commented on 1-module/5-task/index.js
>  }
Тут упали тесты, кажется отрезал на 2 буквы больше.

    Error: Expected 'Вот, что мне хоте...' to be 'Вот, что мне хотело…'.

2024-08-18 14:28 UTC, sebotest3 commented
добавил коммит с решением для 5-й задачи

2024-08-19 12:25 UTC, SinimaWath approved these changes

2024-08-19 12:26 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-08-19 12:26 UTC, merged